import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { chmodSync, copyFileSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import packageInfo from '../package.json' with { type: 'json' };

export const targets = [
  'aarch64-apple-darwin', 'x86_64-apple-darwin',
  'aarch64-unknown-linux-gnu', 'x86_64-unknown-linux-gnu',
];
export const version = packageInfo.version;
const root = fileURLToPath(new URL('../', import.meta.url));
export const archiveName = (target) => `promptly-${version}-${target}.tar.gz`;
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');

export function validateTag(tag) {
  if (!/^\d+\.\d+\.\d+$/.test(version) || tag !== `v${version}`) {
    throw new Error(`Release tag must match package.json: v${version}; received ${JSON.stringify(tag)}`);
  }
}

export function packageBinary(target, binary = 'dist/promptly', output = 'dist/release') {
  if (!targets.includes(target)) throw new Error(`Unsupported archive target: ${target}`);
  const directory = resolve(output);
  mkdirSync(directory, { recursive: true });
  const stage = mkdtempSync(join(tmpdir(), 'promptly-package-'));
  try {
    copyFileSync(resolve(binary), join(stage, 'promptly'));
    chmodSync(join(stage, 'promptly'), 0o755);
    copyFileSync(join(root, 'README.md'), join(stage, 'README.md'));
    copyFileSync(join(root, 'third_party/bun-LICENSE.md'), join(stage, 'bun-LICENSE.md'));
    copyFileSync(join(root, 'third_party/README.md'), join(stage, 'THIRD_PARTY.md'));
    const name = archiveName(target);
    const result = spawnSync('tar', ['-czf', join(directory, name), '-C', stage,
      'promptly', 'README.md', 'bun-LICENSE.md', 'THIRD_PARTY.md'], { encoding: 'utf8' });
    if (result.error) throw result.error;
    if (result.status !== 0) throw new Error(result.stderr);
    const digest = sha256(readFileSync(join(directory, name)));
    writeFileSync(join(directory, `${name}.sha256`), `${digest}  ${name}\n`);
    return name;
  } finally { rmSync(stage, { recursive: true, force: true }); }
}

// Only promote a complete set of artifacts; do not trust uploaded checksum text
// as shell input, paths, or Ruby source.
export function verifyArtifacts(directory) {
  const names = targets.map(archiveName);
  const unexpected = readdirSync(directory).filter((name) => name.endsWith('.tar.gz') && !names.includes(name));
  if (unexpected.length) throw new Error(`Unexpected archives: ${unexpected.join(', ')}`);
  const hashes = {};
  for (const [index, name] of names.entries()) {
    const digest = sha256(readFileSync(join(directory, name)));
    const checksum = readFileSync(join(directory, `${name}.sha256`), 'utf8');
    if (checksum !== `${digest}  ${name}\n`) throw new Error(`Checksum mismatch: ${name}`);
    hashes[targets[index]] = digest;
  }
  return hashes;
}

export function formula(hashes) {
  for (const target of targets) {
    if (!/^[a-f0-9]{64}$/.test(hashes[target] ?? '')) throw new Error(`Invalid checksum: ${target}`);
  }
  const asset = (target) => `url "https://github.com/yungibly/promptly/releases/download/v${version}/${archiveName(target)}"\n      sha256 "${hashes[target]}"`;
  return `# Generated by promptly's release workflow; see scripts/release.js.
class Promptly < Formula
  desc "Procedural generative art for your zsh prompt"
  homepage "https://github.com/yungibly/promptly"
  version "${version}"

  on_macos do
    depends_on macos: :ventura

    on_arm do
      ${asset('aarch64-apple-darwin')}
    end
    on_intel do
      ${asset('x86_64-apple-darwin')}
    end
  end

  on_linux do
    on_arm do
      ${asset('aarch64-unknown-linux-gnu')}
    end
    on_intel do
      ${asset('x86_64-unknown-linux-gnu')}
    end
  end

  uses_from_macos "zsh"

  def install
    bin.install "promptly"
    doc.install "README.md", "bun-LICENSE.md", "THIRD_PARTY.md"
  end

  test do
    assert_equal "promptly #{version}", shell_output("#{bin}/promptly --version").strip
    # Keep this test portable to Homebrew environments without a UTF-8 locale.
    source = shell_output("#{bin}/promptly --seed homebrew --engine prompt --label brew --glyphs ascii")
    assert_match "# Promptly", source
    (testpath/"prompt.zsh").write(source)
    system "zsh", "-fn", testpath/"prompt.zsh"
    output = shell_output("zsh -f -c 'COLUMNS=80; source ./prompt.zsh; print -rP -- \\\"$PROMPT\\\"; promptly_off'")
    assert_match "brew", output
  end
end
`;
}

function main() {
  const [command, ...args] = process.argv.slice(2);
  if (command === 'validate') {
    validateTag(args[0] ?? process.env.RELEASE_TAG);
    console.log(`Release tag matches v${version}`);
  } else if (command === 'package') {
    console.log(packageBinary(...args));
  } else if (command === 'verify' || command === 'formula') {
    const directory = args[0] ?? 'dist/release';
    const hashes = verifyArtifacts(directory);
    const sums = targets.map((target) => `${hashes[target]}  ${archiveName(target)}\n`).join('');
    writeFileSync(join(directory, 'SHA256SUMS'), sums);
    if (command === 'formula') {
      const destination = args[1] ?? join(directory, 'promptly.rb');
      writeFileSync(destination, formula(hashes));
      console.log(`Wrote ${destination}`);
    } else console.log(`Verified ${targets.length} release archives`);
  } else throw new Error('Usage: node scripts/release.js validate TAG | package TARGET [BINARY DIRECTORY] | verify [DIRECTORY] | formula [DIRECTORY FILE]');
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { main(); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
